import numpy as np

tcrdists = np.arange(0, 41, 3)
mincounts = [2, 5, 10]
chains = ['beta']
clusterings = ['leiden']
testmethods = ['fisher']

rule all:
    input:
        [f'results/stats_{chain}_td{max_tcrdist}_mc{mincount}_{testmethod}_{clustering}.csv'
          for chain in chains
          for max_tcrdist in tcrdists
          for mincount in mincounts
          for testmethod in testmethods
          for clustering in clusterings]

rule metaclonotypist:
    output:
        'results/stats_{chain}_td{max_tcrdist}_mc{mincount}_{testmethod}_{clustering}.csv'
    script:
        'Metaclones_script_3.py'

